### ISSUE TITLE
Travis test too long

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#10]
I'm currently setting travis test for our tools. I need to run all the tests within 50 minutes and if a test don't produce log alter 10 min, it fails.

https://travis-ci.org/workflow4metabolomics/xcms/builds/124014197
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

It seems that the group jobs builded from my test cases are too long for TravisCI.

https://github.com/workflow4metabolomics/xcms/blob/master/galaxy/xcms_group/abims_xcms_group.xml#L100

@yguitton @sneumann or anyone else, do you know which method and/or parameters I can set to reduce executing time?

Or do I have too change my input dataset?

Thanks by advance

**Comment by sneumann** [comment]
Hi, you have a pretty large number of peaks per sample, are there memory/swapping issues on the travis host ? Also, you might increase minfrac, to avoid getting 48998 groups. That would result in 
too many NA values anyway. Just my 2c. Yours, Steffen

**Comment by lecorguille** [comment]
I guess I have this large number of peaks because I only kept 4 samples (2 samples / 2 conditions).
Perhaps my datasets must be review a little.

**Comment by lecorguille** [comment]
Is there somewhere a light test/demo dataset for xcms?

**Comment by sneumann** [comment]
I like `library (faahKO)` where you can then `xset <- group(faahko)` and so even skip peak picking :-)

**Comment by lecorguille** [comment]
OK, I will try using those files provide by faahKO and see if the tests are quicker

```
KO:
total 22M
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 ko15.CDF
-rw-r--r-- 1 lecorguille sib 3.5M Apr 19 22:33 ko16.CDF
-rw-r--r-- 1 lecorguille sib 3.5M Apr 19 22:33 ko18.CDF
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 ko19.CDF
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 ko21.CDF
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 ko22.CDF

WT:
total 22M
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 wt15.CDF
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 wt16.CDF
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 wt18.CDF
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 wt19.CDF
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 wt21.CDF
-rw-r--r-- 1 lecorguille sib 3.6M Apr 19 22:33 wt22.CDF
```

**Comment by lecorguille** [comment]
:+1: 
Thanks a lot @sneumann , travis tests pass using 2 files in each condition.
