### ISSUE TITLE
Inf in dataMatrix after fillPeaks

### ISSUE THREAD

**Issue by sneumann** [workflow4metabolomics/xcms#117]
Hi, @MarrSue and I are debugging a case where for one very specific parameter combination 
we get Inf values in the featureValues dataMatrix after fillPeaks.
This was recently discussed in https://github.com/sneumann/xcms/issues/323#issuecomment-433044378
and should be fixed in newer XCMS versions. I had difficulties creating an R script that exactly replicates Sue's W4M history and exhibits the xcms bug locally, so I can't confirm the fix. Yours, Steffen

**Comment by lecorguille** [comment]
Should be fixed with: https://github.com/workflow4metabolomics/xcms/pull/119

**Comment by lecorguille** [comment]
Fix with: https://github.com/workflow4metabolomics/xcms/pull/120
