### ISSUE TITLE
scanrange option

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#14]
ping @yguitton @jfrancoismartin 

In the current wrapper version for xcmsSet, `scanrange` is only available for centWave. In `?xcmsSet`, it seems that this obscure option should be available for all methods?

What do you think about that?

**Comment by jfrancoismartin** [comment]
Sorry I don't use matchfilter but scanrange should work with. This option should be really useful but there was a bug in previous version which leads to wrong eicplot in the diffreport function. So I stopped using it.

**Comment by lecorguille** [comment]
Oki, I will add it for all methods.
Thanks @jfrancoismartin

**Comment by lecorguille** [comment]
Done https://github.com/workflow4metabolomics/xcms/pull/27
Will be available within the xcmsSet-2.0.11

**Comment by lecorguille** [comment]
`docker run -d -p 8080:80 quay.io/workflow4metabolomics/galaxy-workflow4metabolomics:beta`

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by lecorguille** [comment]
- [ ]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin
