### ISSUE TITLE
Empty PDF

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#18]
@yguitton - 22/02/16 to @lecorguille, @melpetera 

> Bonsoir
> 
> j'ai une piste enfin peut-être, pourriez-vous tester en créant deux class samples et pool pour voir?
> normalement j'avais fais les modifs pour que plotTIC et plotBPC gèrent le cas à une seule classe mais bon, c'est  peut-être pas parfait
> 
> dites-moi si ça règle qq chose
> Yann

**Comment by lecorguille** [comment]
Is it still an issue?

**Comment by melpetera** [comment]
If this concerned the fact that when having only one group  (i.e. one folder of raw data) the BPC and TIC pdf files do not contain any graph, yes this is still an issue (that does not concern cases with two groups). I can share you a galaxy history with "light" data if you need.

**Comment by yguitton** [comment]
I have dicovered that my changes proposed in may 2015 are not in the prod version. I have created a patch version of xcms libr.r but there are 2 travis errors?

**Comment by lecorguille** [comment]
Fixed and merged by @yguitton: https://github.com/workflow4metabolomics/xcms/pull/21
