### ISSUE TITLE
scan range in xcmsSet not easy to use

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/xcms#19]
Can we change the tool in order to use RTrange instead of scan range?
It is sometime confusing for users to enter a scan number instead of a RT. users are used to cut their chromatogramme between min and max RT values not between scan numbers. And sometimes scan numbers read in in silicos viewer are not the on read by xcms.

**Comment by sneumann** [comment]
Hi, just stumbled upon this, @jotsetung worked in this part of the code. 
So we'd know where to put that function.

**Comment by jotsetung** [comment]
Good suggestion @yguitton . I'll implement that.

**Comment by yguitton** [comment]
Great!  Thanks for your time

**Comment by lecorguille** [comment]
As suggested [here](https://github.com/workflow4metabolomics/xcms/issues/80#issuecomment-367232961), we should now implement `MSnBase::filterRt`, `MSnBase::filterAcquisitionNum` (which would be the same than using scanrange) and `MSnBase::filterMz` in findChromPeaks/xcmsSet wrapper

**Comment by lecorguille** [comment]
Done and will be available in the xcms3 wrappers: https://github.com/workflow4metabolomics/xcms/pull/84/commits/e0fb1706860067451989ec1d281a8314072274e7
