### ISSUE TITLE
Non-unique identifiers for ions

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/xcms#22]
Sometimes there are redundant ion identifiers, especially when using RT in minutes (for example "M123.32T11" for two different ions with mass 123.32 and RT 10.6 min and 11.4 min). 

Since identifiers are meant to be unique, something must be done (currently users add more decimal places for mass, change RT in seconds and/or modify identifiers themselves).

**Comment by lecorguille** [comment]
Are we agree that it's important during the peaklist export (currently camera.annotate, camera.combinexannot and soon xcms.fillpeaks) ?

If so, do you want that those redundant ion identifiers to be spotted and corrected automatically by increasing the number of digit?

**Comment by lecorguille** [comment]
Crossref: https://github.com/workflow4metabolomics/camera/issues/11

**Comment by lecorguille** [comment]
Done for FillPeaks-2.0.8: https://github.com/workflow4metabolomics/xcms/blob/bfb80b96ab0497a8d1fd853b779a26897f765929/galaxy/xcms_fillpeaks/abims_xcms_fillPeaks.xml#L45

**Comment by yguitton** [comment]
just a note they're is a function called xcmss:::groupnames in xcms that can be used (with function(xcmsSet object, mzdec = 0, rtdec = 0, template = NULL)  with that even if a duplicate name is found it will be converted to MxTy_z

**Comment by lecorguille** [comment]
@yguitton Good suggestion but ... how do you use `groupnames`

I try without template 
```R
ids <- groupnames(xset, mzdec = numDigitsMZ, rtdec = numDigitsRT, template = NULL)
```
but:
```
|  Error in strsplit(template[1], "[T_]") : non-character argument
|  Calls: getPeaklistW4M -> groupnames -> groupnames -> .local -> strsplit
```

Help is welcome because they isn't so much documentation 👎

**Comment by lecorguille** [comment]
@melpetera is `make.unique` is enough: (here)[https://github.com/workflow4metabolomics/xcms/blob/71d1be4a149301f573e7d05de467545c644d24d0/src/xcms_w4m_script/lib.r#L20]

**Comment by lecorguille** [comment]
@melpetera @yguitton UP!

**Comment by melpetera** [comment]
About make.unique: I would add the sep="_" argument because identifiers already have points in it.
But I think this can do!

**Comment by lecorguille** [comment]
From xcms.group 2.1.1 and xcms.fillpeaks 2.1.1 
as discussed here: https://github.com/workflow4metabolomics/xcms/issues/36

**Comment by lecorguille** [comment]
`docker run -d -p 8080:80 quay.io/workflow4metabolomics/galaxy-workflow4metabolomics:beta`

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by melpetera** [comment]
Tested on dev galaxy instance!
It is ok for me.

**Comment by lecorguille** [comment]
- [X]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin

**Comment by lecorguille** [comment]
Validated
