### ISSUE TITLE
Exporting a peak table in xcms.fillpeaks

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#23]
without have to use CAMERA
So maybe split the tool camera or add a new output within fillpeaks?

**Comment by lecorguille** [comment]
@workflow4metabolomics/ms Check that: https://github.com/workflow4metabolomics/xcms/pull/29

**Comment by lecorguille** [comment]
TODO:

- [ ] Do as suggested by @yguitton https://github.com/workflow4metabolomics/xcms/issues/22#issuecomment-269042323
- [ ] Propose to convert RT in minute

**Comment by lecorguille** [comment]
@yguitton @melpetera @jfrancoismartin 

If you have some code to generate the peaklist (and ids) as camera.peaklist or xcms.diffreport, I'm interesting in.
Because, I'm afraid about synchronization issue between camera, diffreport outputs and this export when there are some duplicate ids.

I'm working on camera.annotate exports. The native export deal perfectly with duplicates by adding _1 and _2 ... But when we reformat the ids (minutes, number of digits), we have to be careful.

I'm expecially worry about the ids I'm generating in this tools.

**Comment by lecorguille** [comment]
From xcms.fillpeaks 2.1.1

**Comment by lecorguille** [comment]
`docker run -d -p 8080:80 quay.io/workflow4metabolomics/galaxy-workflow4metabolomics:beta`

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by melpetera** [comment]
Exports in group and fillpeaks work well. Ok for me!

**Comment by lecorguille** [comment]
- [X]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin

**Comment by lecorguille** [comment]
Validated
