### ISSUE TITLE
annotateDiffrepot bug

### ISSUE THREAD

**Issue by fgiacomoni** [workflow4metabolomics/xcms#25]
OTRS - 2016112910000118 
Si on opte pour RT en minutes et qu'on veut utiliser le annotateDiffreport en tant que
variableMetadata pour faire une filtration ou qualityMetrix, ca plante car
l'identificateur d'ions est resté en seconde et du coup, il n'y a pas coh?rence entre les
fichiers dataMatrix et variablesMetadata.
Merci de votre attention
JF

**Comment by lecorguille** [comment]
mv in camera repository: https://github.com/workflow4metabolomics/camera/issues/12
