### ISSUE TITLE
Exporting a peak table in xcms.group

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/xcms#35]
The idea is to do the same as decided in #23 for fillpeaks, this time for group module.

**Comment by lecorguille** [comment]
From xcms.group 2.1.1

**Comment by lecorguille** [comment]
`docker run -d -p 8080:80 quay.io/workflow4metabolomics/galaxy-workflow4metabolomics:beta`

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by melpetera** [comment]
Tested on dev galaxy instance. 
Works well! Ok for me.

**Comment by lecorguille** [comment]
- [X]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin

**Comment by melpetera** [comment]
Didn't notice before but the output names are  "fillpeak"ed!

**Comment by lecorguille** [comment]
@melpetera Indeed, thanks!

**Comment by lecorguille** [comment]
Fix: https://github.com/workflow4metabolomics/xcms/commit/b8ea02b3d37550c33dcf8e099fe8c636287b0865
And push to the dev

**Comment by melpetera** [comment]
And validated. Ok for me.

**Comment by lecorguille** [comment]
Thanks
