### ISSUE TITLE
New column: "namecustom"

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/xcms#36]
This issue concerns the peak table export in xcms.group and xcms.fillpeaks. 

The idea is to:
- keep default ion identifiers,
- add a "namecustom" column corresponding to what a user asks about decimal places for mass and retention time, and convertion of rt into minutes.

**Comment by lecorguille** [comment]
From xcms.group 2.1.1 and xcms.fillpeaks 2.1.1

**Comment by lecorguille** [comment]
`docker run -d -p 8080:80 quay.io/workflow4metabolomics/galaxy-workflow4metabolomics:beta`

**Comment by lecorguille** [comment]
Available within the dev galaxy instance

**Comment by melpetera** [comment]
Tested on dev galaxy instance!
Options work well. It is ok for me. 

Funny note: the "_x" used in original ID when same ID is also added to the namecustom column. I do not know if it is a good or bad thing yet (ensure unique names in all cases, but useless most of the time), so I would recommend to leave it this way for the moment, and see later whether changes are needed depending on user feedback.

**Comment by lecorguille** [comment]
- [X]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin

**Comment by lecorguille** [comment]
Validated
Many thanks
