### ISSUE TITLE
Bug with the deleteXmlBadCharacters step

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#4]
With @sneumann we found that is step originally design to delete "é", "è" characters from `<parentFile fileName="file://C:/data/métabo/foobar.RAW"` where raw files are stored.

2 solutions:
- enhancement this feature by being more specific on the fileName attribute
- propose a PR on xcms to deal with those characters

**Comment by mmonsoor** [comment]
Ok, thanks for telling me about this.

**Comment by sneumann** [comment]
Hi, I can't reproduce the issue. The attached file contains accents in different places. 
Does it work on your setup ? If yes, can up upload a (small) file that breaks ? 
Often, problems with accents are related to wrong encoding issues. 
Check the beginning of the mzML file: `<?xml version="1.0" encoding="utf-8"?>`
and also your `sessionInfo()` for the LOCALE settings. 

[Challenge-19-accents.zip](https://github.com/workflow4metabolomics/xcms/files/192990/Challenge-19-accents.zip)

````
> xr <- xcmsRaw("Challenge-19-accents.mzML")
> xr
An "xcmsRaw" object with 2 mass spectra

Time range: 0.2-0.8 seconds (0-0 minutes)
Mass range: 100.0026-968.9352 m/z
Intensity range: 709.857-1854070 

MSn data on  0  mass(es)
	with  0  MSn spectra
Profile method: bin 
Profile step: 1 m/z (870 grid points from 100 to 969 m/z)

Memory usage: 0.0384 MB
> xs <- xcmsSet(c("Challenge-19-accents.mzML"))
150:0 200:0 250:0 300:0 350:0 400:0 450:0 500:0 550:0 600:0 650:0 700:0 750:0 800:0 850:0 900:0 950:0 
Warning message:
No peaks found in sample Challenge-19-accents 
> filepaths(xs)
[1] "/tmp/Challenge-19-accents.mzML"
> ms <- openMSfile("Challenge-19-accents.mzML", backend="pwiz")
> instrumentInfo(ms)
$manufacturer
[1] "Thermo Scientific"

$model
[1] "Q Exactive"

$ionisation
[1] "electrospray ionization"

$analyzer
[1] "quadrupole"

$detector
[1] "inductive detector"

$software
[1] "Xcalibur 2.5-204201/2.5.0.2042 èéëÖÄÜöäµ"

$sample
[1] ""

$source
[1] ""
````

````
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] xcms_1.47.2         Biobase_2.30.0      ProtGenerics_1.3.3 
[4] BiocGenerics_0.16.1 mzR_2.5.3           Rcpp_0.12.3        
````

**Comment by mmonsoor** [comment]
@sneumann 

Hi, i'm Misharl Monsoor from the ABIMS team in Roscoff. I can't attach the file here, because it's too heavy. I

**Comment by sneumann** [comment]
Yes, I can confirm the issue with an UTF-8 locale (which is standard nowadays):

````
> xr <- xcmsRaw("pool8.mzXML")
Error in readChar(filename, 1024) : invalid UTF-8 input in readChar()
> traceback()
6: readChar(filename, 1024)
5: mzR:::rampIsFile(object)
4: .local(object, ...)
3: xcmsSource(filename)
2: xcmsSource(filename)
1: xcmsRaw("pool8.mzXML")
````

If you run R with the basic C locale: ````LANG=C R```` the issue does not occur:
````
> xr <- xcmsRaw("pool8.mzXML")
> xr
An "xcmsRaw" object with 4797 mass spectra
````

Yours,
Steffen

**Comment by lecorguille** [comment]
Thanks Steffen @sneumann 

I have just integrate `LANG=C` on my dev branch: 
https://github.com/workflow4metabolomics/xcms/blob/planemo_test/galaxy/macro/macros.xml#L18

We will test that ASAP

**Comment by mmonsoor** [comment]
@sneumann We have tested with the integration of LANG=C, and we confirm that it does work! Thanks a lot for your precious help.

**Comment by lecorguille** [comment]
I merged in the master branch
I close this issue
Thanks @sneumann for the fix and @mmonsoor for your feedback
