### ISSUE TITLE
Name the dataset with the input name

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#40]
At least for the single file mode
- xset.RData
- xset.RData
- xset.RData
- xset.RData
- xset.RData
- xset.RData
- xset.RData
- xset.RData

**Comment by lecorguille** [comment]
https://github.com/workflow4metabolomics/xcms/pull/45

**Comment by melpetera** [comment]
Tested and validated (single files and zip files). Handy feature!

**Comment by lecorguille** [comment]
- [X]  validated by @melpetera 
- [ ]  validated by @yguitton 
- [ ]  validated by @jfrancoismartin

**Comment by yguitton** [comment]
Great

**Comment by lecorguille** [comment]
Valided
Many thanks
