### ISSUE TITLE
Decimal places in xcms.group graphical output

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/xcms#47]
In the xcms.group graphical output (Rplots.pdf), plot names correspond to corresponding mz slices. Mz values are written with 2 decimal places (for exemple "164.94 − 164.96"). 

The problem is that if you choose for any reason to consider narrow mz slices (changing mzwid to 0.005 for example), then you will have things like "164.95 − 164.95" and will not actually know if it is close or not to your maximum mz width. 

Would it be possible for the plot titles to have more decimal places? There is room for longest names, so maybe 4 decimal places would be ok?

**Comment by lecorguille** [comment]
Can we imagine that this issue should be raised to the xcms development (or other loaded package)?

**Comment by melpetera** [comment]
I checked where it is "decided" that it is 2 decimal places, and it is in the xcms package. 
In this line, somewhere: 
`plot(den, main = paste(round(min(speakmat[,"mz"]), 2), "-", round(max(speakmat[,"mz"]), 2)))`
So, I agree it could be relevant to raise it as an issue for de xcms development team, asking to convert these "2" into an adjustable parameter.

**Comment by lecorguille** [comment]
Great!
Put a link of this issue in the xcms one. That way, we will be able to follow the development.

**Comment by lecorguille** [comment]
Fix by https://github.com/workflow4metabolomics/xcms/pull/84/commits/45270a82fae23bd4f216684ce2e1f67c217cfea6 in the xcms3 wrapper
