### ISSUE TITLE
Error when reading mzXML files (due to accent é è )

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/xcms#52]
Sometimes during MS files life they are stored under filepaths with accent (e.g in french metabolomics is m**é**tabolomique)
and so when converting to mzXML (or other format) sometimes those paths are kept in the file and we get error.

invalid UTF-8 input in readChar()  ligne <parentFile fileName="file:///D:/JPA/Laits-2015-06-10-Exactive (Metabolomique R�cap)/./211114031_S5_.raw" for exemple

**Comment by lecorguille** [comment]
@sneumann You already help me with an issue with those kind of characters.
Your advice was to use [`LANG=C Rscript `](https://github.com/workflow4metabolomics/xcms/blob/master/galaxy/macro/macros.xml#L17)
In this case, it seems to not be enough.
Do you have an other tricks?
Many thanks

**Comment by sneumann** [comment]
Can you provide a small test file ? Yours, Steffen

**Comment by yguitton** [comment]
HI @sneumann , here enclosed two files the V1 generate the reported error and V2 not. The only difference is that i have manually removed the é  in Metabolomique in V2 xml.
Thanks for your help


<parentFile fileName="file:///D:/JPA/Laits-2015-06-10-Exactive (Métabolomique Recap)/./211114031_S5_.raw"
                fileType="RAWData"
                fileSha1="fbfae5c6fea3d3df5f51aedd34d58238786a1902"/>

[mzXML_files_forTest.zip](https://github.com/workflow4metabolomics/xcms/files/896242/mzXML_files_forTest.zip)

**Comment by sneumann** [comment]
Hi, sorry, can't reproduce here. I tried 
`export LOCALE="C" ; echo 'library(xcms);xcmsRaw("211114031S3V1.mzXML") ; sessionInfo()' | R --vanilla
` and it just worked. What is your locale as reported by `sessionInfo()` ?

**Comment by lecorguille** [comment]
Seems fix since: https://github.com/workflow4metabolomics/xcms/commit/d649c255dcb37107266de73fc073fc01615f6359
@yguitton I have just tested your files in the prod instance and it works.
