### ISSUE TITLE
Add minsamp agrument in group 

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/xcms#59]
group function parameters are not complet, the minsamp argument is missing, can we add it in the advanced options list?

**Comment by lecorguille** [comment]
It should be done in the future version of the wrapper [xcms.group 3.0.0.0](https://github.com/workflow4metabolomics/xcms/pull/78/commits/dc38d78dcdb4cd98f17deaeacc3528aa77fec8b0)
