### ISSUE TITLE
xcmsSet parameter in XCMS Summary

### ISSUE THREAD

**Issue by SylvainChereau** [workflow4metabolomics/xcms#62]
Redundancy is created when using dataset collection mode. XCMS summary generates a line of xcmsSet parameters for each datafile (off course they are the same for each file of dataset collection).
[xcms_summary_html.zip](https://github.com/workflow4metabolomics/xcms/files/1096988/xcms_summary_html.zip)

**Comment by lecorguille** [comment]
Yes, I know that and indeed I should check if all the parameters are the same and if it's the case only display on set.

**Comment by lecorguille** [comment]
It should be done in the future version of the wrapper [xcms.summary 3.0.0.0](https://github.com/workflow4metabolomics/xcms/blob/a2ec7dfe8bfb54820eb6f0f65aaf18c7551f36d9/tools/xcms_summary/xcms_summary.r#L46)
