### ISSUE TITLE
TODO add verbose.column and fitgauss (to add to parameter completness)

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/xcms#63]
we have a user request regarding xcmsset fitgauss option and verbose.column=TRUE

should be quite easy to add those two options

Note be careful with verbose.column as it will add new columns to xset@peaks tables. those columns can be used only if people do look at each file peak tables individually

**Comment by yguitton** [comment]
new email from user to add profparam in xcmsSet centWave allowing the addition of profparam = list(step=0.005)

**Comment by yguitton** [comment]
I just tried to add profparam as new expert parameter along with verboseColumn, but not sure that the outputs is still compatible with next steps (group, fillpeaks and variableMetatdata export can you check than @lecorguille  ?

**Comment by lecorguille** [comment]
Done in the new xcms3 wrappers
https://github.com/workflow4metabolomics/xcms/pull/78
