### ISSUE TITLE
xcms_xcmsset gives empty result

### ISSUE THREAD

**Issue by bernt-matthias** [workflow4metabolomics/xcms#66]
When running xcms_xcmsset  (revision 15646e937936) I get an empty result. The resulting dataset is marked as successful, but its empty. 

In the dataset preview I see the following text: 

`code for methods in class "Rcpp_Ramp" was not checked for suspicious field assignments (recommended package 'codetools' not available?)
`

I uploaded the input to https://oc.ufz.de/index.php/s/j4aPVY6iwlv6WU7 with password xcms. 

Options: 
Input: see OC
Scan range option: hide
Extraction method for peaks detection: centWave
Max tolerated ppm m/z deviation in consecutive scans in ppm: 25
Min,Max peak width in seconds: 20,50
Advanced options: hide

**Comment by lecorguille** [comment]
Hi,
One which Galaxy instance did you use the xcms tools?

**Comment by bernt-matthias** [comment]
I installed it on our instance (currently the dev branch).

**Comment by lecorguille** [comment]
Hum ... I have just tested using our [Flavor](https://github.com/workflow4metabolomics/w4m-docker#step-1-running-the-docker-container):
```
docker run -d -p 8080:80 workflow4metabolomics/galaxy-workflow4metabolomics
```
And no problem for me 

Did you use the Conda package or the tool_dependencies ?

**Comment by bernt-matthias** [comment]
The "Dependency Resolver Details" of 'xcms_xcmsset' list r-snow     0.4_1, bioconductor-xcms     1.46.0, and r-batch     1.1_4. All use Conda as Resolver.

**Comment by bernt-matthias** [comment]
How can I help to debug this further? I can see the command line in the logs and could try it directly. But I do not know which of the Rscript binaries that are found in my galaxy directory is used.

**Comment by lecorguille** [comment]
You can enable this option in your galaxy.ini:
[`cleanup_job = onsuccess`](https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L1305)

That way, you will be able to browse the working directory and launch the script named `tool_script.sh`(or something like that). It sets the Conda environment if there is one.

In the log, you can also check if it really manages to use the conda packages through a mulled environment or using aggregation of individual packages.
```
galaxy.tools.deps DEBUG 2017-08-28 09:52:04,481 Using dependency bowtie2 version 2.3.2 of type conda
galaxy.tools.deps DEBUG 2017-08-28 09:52:04,481 Using dependency samtools version 1.3.1 of type cond
galaxy.jobs.command_factory INFO 2017-08-28 09:52:04,535 Built script [/w/galaxy/galaxy3/database/job_working_directory/014/14148/tool_script.sh] for tool command [[ "$CONDA_DEFAULT_ENV" = "/w/conda/galaxy3/_conda/envs/mulled-v1-cf272fa72b0572012c68ee2cbf0c8f909a02f29be46918c2a23283da1d3d76b5" ] ||
```

**Comment by bernt-matthias** [comment]
Thanks a lot for the info. 

The problem seemed to be a misconfiguration of our job runner. 

Sorry for the inconvenience.

**Comment by lecorguille** [comment]
No problem
Thanks for your interest in our project :)
