### ISSUE TITLE
xcmsSet , in file name

### ISSUE THREAD

**Issue by bernt-matthias** [workflow4metabolomics/xcms#68]
If a file with a ',' in the file name is used as input then the link is not created properly (the name of the link is the prefix of the filename up to the comma) and xcms does not find input data:

```
Error in xcmsSet(".", nSlaves = 1, method = "centWave", ppm = 25, peakwidth = c(10,  : 
  No NetCDF/mzXML/mzData/mzML files were found.
```

Seems to be related to: https://github.com/workflow4metabolomics/xcms/issues/65 (some escaping seems to be necessary).

**Comment by lecorguille** [comment]
Oh a `,` in the filename.
I never expected that :)

Are you using as input a 'single' file or a zip file?

**Comment by bernt-matthias** [comment]
Input is a single file. Actually I do not know the intension of the comma. One of our users just send me a bug report. I guess there is a float value encoded in the file name and germans use ',' instead of '.' in floats. I could ask if you are interested. 

Input is a single file.

**Comment by lecorguille** [comment]
@bernt-matthias It should be fixed in the future wrappers for xcms3 https://github.com/workflow4metabolomics/xcms/pull/84/commits/1e6ed0300ba6105ac0236d04b66ae44d12851aeb
