### ISSUE TITLE
XCMS merger: sampleMetadata file generation if not as input

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/xcms#72]
Dear Santa @lecorguille Claus,

When you use XCMS merger without providing any sampleMetadata file, this means that you have no ready "reference" file for the processing step following xcms analyses. 

In addition, it is not always straigthforward to construct the sampleMetadata file, knowing that sample identifiers are raw files' names that can be automatically generated by machine's software with unfriendly automatic names. 

The possibility to use an empty sampleMetadata file with already the right identifiers, as it is provided with the zip option, is very handy and reduce significantly the misscase errors compared to manual listing in addition to saving time. 

For all this reasons I would strongly recommand to add, when not provided as input, a sampleMetadata file as output with identifiers as first column (of course), and maybe just a second column 'class' with a constant value (for example 'no groups' ou "single group'). 

Thank you for you time.
M. who behaved really well this year.

**Comment by lecorguille** [comment]
Good idea!

**Comment by yguitton** [comment]
Can be good also to try to read insidemzml file the acquisution date and
create injectionOrder.... Sneuman already build something like that i
think...

Yann



Le 14 déc. 2017 15:37, "Gildas Le Corguillé" <notifications@github.com> a
écrit :

**Comment by lecorguille** [comment]
@melpetera Done in the future XCMS3 wrappers https://github.com/workflow4metabolomics/xcms/pull/84/commits/ac67b843b15c80e8f8ad44b2702189493d7552f0

@yguitton I didn't found any information about the injectionOrder in the xdata object.
@jotsetung Do you know if those informations are available nested somewhere?

**Comment by jotsetung** [comment]
Re injectionOrder... I use to pass the injection index along with the pheno data file/table in `readMSData`, e.g. in a column named `injection_index`. If you read the data than into an object called e.g. `xdata` you can access it with `xdata$injection_index`.

**Comment by lecorguille** [comment]
Thanks @jotsetung, it is also what we usually ask to our users. 

So let say that we can't guess the injection order only with the xdata.

@yguitton I prefer to not have to parse the xml files to fetch those informations.
I'm closing the issue, but feel free to reopen it if you want
