### ISSUE TITLE
XCMS3: review findChromPeaks/xcmsSet parameters

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#80]
# findChromPeaks/xcmsSet

## Generale
- Advanced Options
  - [x]  MSnBase::filterAcquisitionNum (previously scanrange)
  - [x]  MSnBase::filterRt
  - [x]  MSnBase::filterMz

## [CentWaveParam()](https://rdrr.io/bioc/xcms/man/findChromPeaks-centWave.html#heading-2)
- Basic Options
  - [x]  ppm: 25
  - [x]  peakwidth: 20, 50
- Advanced Options
  - [x]  snthresh: 10
  - [x]  prefilter: 3, 100
  - [x]  mzCenterFun: wMean
  - [x]  integrate: 1
  - [x]  mzdiff: -0.001
  - [x]  fitgauss: FALSE
  - [x]  noise: 0
  - [x]  verboseColumns: FALSE
    - List of regions-of-interest (ROI)
    - [x]  roiList length: 0
    - [x]  firstBaselineCheck TRUE
    - [x]  roiScales length: 0

## [CentWavePredIsoParam()](https://rdrr.io/bioc/xcms/man/findChromPeaks-centWaveWithPredIsoROIs.html#heading-2)
- Basic Options
  - [x]  ppm: 25
  - [x]  peakwidth: 20, 50
- Advanced Options
  - [x]  snthresh: 10
  - [x]  prefilter: 3, 100
  - [x]  mzCenterFun: wMean
  - [x]  integrate: 1
  - [x]  mzdiff: -0.001
  - [x]  fitgauss: FALSE
  - [x]  noise: 0
  - [x]  verboseColumns: FALSE
- List of regions-of-interest (ROI)
  - [x]  roiList length: 0
  - [x]  firstBaselineCheck TRUE
  - [x]  roiScales length: 0
  - [x]  snthreshIsoROIs: 6.25
  - [x]  maxCharge: 3
  - [x]  maxIso: 5
  - [x]  mzIntervalExtension: TRUE
  - [x]  polarity: unknown

## [MatchedFilterParam()](https://rdrr.io/bioc/xcms/man/findChromPeaks-matchedFilter.html#heading-2)
- Basic Options
  - [x]  fwhm: 30
  - [x]  binSize: 0.1 (previously step)
  - [x]  impute: none (previously profmethod)
    - [x]  baseValue:
    - [x]  distance:
- Advanced Options
  - [x]  impute: none (previously profmethod)
    - [x]  baseValue:
    - [x]  distance:
  - [x]  sigma: 12.73994
  - [x]  max: 5
  - [x]  snthresh: 10
  - [x]  steps: 2
  - [x]  mzdiff: 0.6
- No yet integrated
  - [ ]  index: FALSE

## [MSWParam()](https://rdrr.io/bioc/xcms/man/findPeaks-MSW.html#heading-2)
- Basic Options
  - [x]  snthresh: 3
  - [x]  verboseColumns: FALSE
  - [x]  scales: 1,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,36,40,44,48,52,56,60,64
  - [x]  peakScaleRange: 5
  - [x]  ampTh: 0.01
- No yet integrated
  - [ ]  nearbyPeak: TRUE
  - [ ]  minNoiseLevel: 0.003333333
  - [ ]  ridgeLength: 24
  - [ ]  peakThr:
  - [ ]  tuneIn: FALSE
- Missing?
  - [ ]  winSize_noise
  - [ ]  SNR_method

## [MassifquantParam()](https://rdrr.io/bioc/xcms/man/findChromPeaks-massifquant.html#heading-2)
- No yet integrated
  - [ ]  ppm: 25
  - [ ]  peakwidth: 20, 50
  - [ ]  snthresh: 10
  - [ ]  prefilter: 3, 100
  - [ ]  mzCenterFun: wMean
  - [ ]  integrate: 1
  - [ ]  mzdiff: -0.001
  - [ ]  fitgauss: FALSE
  - [ ]  noise: 0
  - [ ]  verboseColumns: FALSE
  - [ ]  criticalValue: 1.125
  - [ ]  consecMissedLimit: 2
  - [ ]  unions: 1
  - [ ]  checkBack: 0
  - [ ]  withWave: FALSE

## I NEED YOU! :)
So dear @workflow4metabolomics/ms, (and if you have 5 minutes: @sneumann, @jotsetung) : 
 - I need you to tell me which parameters we should expose by default or in the advanced section or not exposed at all.
 - I also need you because I can't find some parameters "Missing?"

If you want, you can use the same checklist as me ([here](https://gist.githubusercontent.com/lecorguille/20ac401a5bebf775e08ef3019d16572d/raw/0461587021666bd75c20db79afb0e41ccb8aa4e1/gistfile1.txt)) and move items.

Many thanks by advanced

**Comment by jotsetung** [comment]
Regarding `scanrange`: this is no longer supported (and needed). In the `xcmsSet` function, this argument was not used by all chromatographic peak detection methods anyway. In the new workflow, the data object (a `OnDiskMSnExp`) can/should be filtered before chromatographic peak picking. For this there are the functions `filterRt`, `filterAcquisitionNum` (which would be the same than using `scanrange`) and `filterMz`.

So, ideally, it would be cool if you allowed the user to first have a look at the e.g. base peak chromatogram of an experiment and then let him/her decide to filter on a certain rt range, if desired.
The BPC could be extracted and plotted with (`data` being the `OnDiskMSnExp`):
```{r}
bpc <- chromatogram(data, aggregationFun = "mean")

plot(bpc)
```

**Comment by jotsetung** [comment]
Regarding `profmethod`: previously, a *profile* matrix (which is in essence just a matrix with intensities for discrete retention times and m/z values, with the m/z values representing binned values) was created for each chrom peak detection method, although only *matchedFilter* needed one.

Now you have to specify the binning method exclusively using the `MatchedFilterParam`. What was previously called `step` is now the `binSize` (hope that it is now clearer to the user what this value means, i.e. that values are aggregated in m/z bins of size `binSize`). 
What was also a little unclear before was that the `profmethod` was actually a combination of *binning* and *missing value imputation*. I've now separated the two. So, with `MatchedFilterParam` the data will always be binned prior to the chromatographic peak detection, (using `binSize`). In addition the imputation can be specified with the `impute` parameter. The corresponding new settings for the *old* `profmethod` are:
+ `profmethod = "bin"` -> `impute = "none"`.
+ `profmethod = "binlin" -> `impute = "lin"`.
+ `profmethod = "binlinbase"` -> `impute = "linbase"`.
+ `profmethod = "intlin"` -> `impute = "intlin"`.
The additional parameters `baseValue` and `distance` are for `"linbase"`. See help of `?imputeLinInterpol` for a detailed description and the mapping of these settings to the *old* parameters.

**Comment by lecorguille** [comment]
@jotsetung Many thanks! It's clearer

**Comment by lecorguille** [comment]
roi* parameters in `CentWave` and `CentWavePredIso` are a little confused for me 

Honestly, I don't know what are exactly regions-of-interest. Are there some ranges of mz and rt, you will focus your analyse on?

Anyway!

### Question1 - about `CentWave` and `CentWavePredIso`
Should we need to provide a `roiList` to actually use those parameters : `firstBaselineCheck` and `roiScales`

### Question2 - about `CentWavePredIso`
What are the dependences (if any) between those parameters?
- roiList
- firstBaselineCheck
- roiScales
- snthreshIsoROIs: 6.25
- maxCharge: 3
- maxIso: 5
- mzIntervalExtension: TRUE
- polarity: unknown

### Question3 - about `CentWave` and `CentWavePredIso`
Is `CentWavePredIso` a kind of classic `CentWave` if we don't provide any roiList?

Many thanks by advanced @yguitton @jfrancoismartin and @jotsetung (if you don't mind to help me again 👍 )

**Comment by sneumann** [comment]
@treutler might also be able to chime in. Yours Steffen

---
I blame Android for the brevity and typos

**Comment by Treutler** [comment]
ROIs: Regions-of-interest (ROIs) are two-dimensional intervals in m/z and rt. These are determined heuristically (very fast) prior to the peak-picking-step by `centWave` to limit the (much slower) `centWave` algorithm to those ROIs instead of the full data.

Question 1: Users had the option to do a targeted peak picking in the old xcms by supplying a `roiList`. Hence, the peak-picking-step is limited (and also forced) to those ROIs. The usual use case is the untargeted peak picking and thus the user usually does not supply an `roiList`. However, the supply of a `roiList` is necessary for `CentWavePredIso`.

Question 2: 
- roiList: analog to `CentWave`
- firstBaselineCheck: analog to `CentWave`
- roiScales: analog to `CentWave`
- snthreshIsoROIs: analog to `snthresh` in `CentWave`
- maxCharge and maxIso: both determine the prediction of isotope-ROIs
- mzIntervalExtension: weakly related to `maxCharge` and `maxIso`
- polarity: is not used as long as variable `addNewAdductROIs` is set to `FALSE`

Question 3: 
No. If not supplied, `CentWave` heuristically determines a list of ROIs de novo and does hence untargeted peak picking. `CentWavePredIso` can be seen as an extension of `CentWave` towards a more exhaustive picking of isotope peak. `CentWavePredIso` does execute `CentWave` two times.

I am happy to help!

**Comment by lecorguille** [comment]
@Treutler Many thanks for your help
I have updated the parameters list above.
