### ISSUE TITLE
XCMS3: review adjustRtime/retcor Obiwarp parameters

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#81]
# adjustRtime/retcor Obiwarp

## [Obiwarp()](https://rdrr.io/bioc/xcms/man/adjustRtime-obiwarp.html#heading-2)
- Basic Options
  - [x]  binSize: 1
- Advanced Options
  - [x]  centerSample:
  - [x]  response: 1
  - [x]  distFun: cor_opt
  - [x]  gapInit: 0.3
  - [x]  gapExtend: 2.4
  - [x]  factorDiag: 2
  - [x]  factorGap: 1
  - [x]  localAlignment: FALSE
  - [x]  initPenalty: 0

## I NEED YOU AGAIN! :)
The same as for [findChromPeaks/xcmsSet parameters](https://github.com/workflow4metabolomics/xcms/issues/80).
So far, we don't expose so many arguments for the method Obiwrap.
Thus dear @workflow4metabolomics/ms, (and if you are interesting in: @sneumann, @jotsetung) : 
 - I need you to tell me which parameters we should expose by default or in the advanced section or not exposed at all.

If you want, you can use the same checklist as me ([here](https://gist.githubusercontent.com/lecorguille/98dcfba895b1f0d35c58039284b0dcab/raw/e11a58e7a1e80764b0e1e0100f9d98b494daa171/gistfile1.txt)) and move items.

Many thanks by advanced

**Comment by jotsetung** [comment]
Have a look at `?ObiwarpParam` for some details on the parameters. Most users will most likely not change them at all, but it would be good to expose all of them (for advanced users).

**Comment by lecorguille** [comment]
Done https://github.com/workflow4metabolomics/xcms/pull/78/commits/52d1e5e85c2f92613e567a0a26eccbc3d80d6a91
