### ISSUE TITLE
XCMS3: review fillChromPeaks/fillpeaks parameters

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#82]
# fillChromPeaks/fillpeaks

## [Parameters](https://rdrr.io/bioc/xcms/man/fillChromPeaks.html)
- Basic Options
- Advanced Options
  - [x]  expandMz: 0
  - [x]  expandRt: 0
  - [x]  ppm: 0

~~- Missing?~~
 - [ ]  ~~method: chrom or MSW~~

## I STILL NEED YOU! :)
So dear @workflow4metabolomics/ms, (and if you have 1 minutes: @sneumann, @jotsetung) : 
 - I need you to tell me which parameters we should expose by default or in the advanced section or not exposed at all.
 - I'm also wondering if it's normal that I can't find any setting for the method `chrom` or `MSW`

If you want, you can use the same checklist as me ([here](https://gist.githubusercontent.com/lecorguille/c90167d446864daf6a13448f16907e82/raw/f3eb8197d28e7b19c3b1309a563c6f44bd955176/gistfile1.txt)) and move items.

Many thanks by advanced

**Comment by jotsetung** [comment]
You don't need the `method` parameter anymore. The `XCMSnExp` object keeps track of what has been performed. It contains also the parameter object that was used for the chromatographic peak detection. Depending on that it uses the correct approach to fill in missing peak data. For `MatchedFilterParam` it fills in data from the *profile* matrix while it uses the raw data for others (like `CentWaveParam`). Previously, peak data was always integrated from the *profile* matrix, even if peak detection was, e.g. for centWave not performed on that.

The new parameters `expandMz`, `expandRt` and `ppm` allow to increase the area (in m/z, retention time using absolute or relative values) from which the signal is integrated. This is a new feature that was not present in the old `fillPeaks`.

**Comment by lecorguille** [comment]
@jotsetung Thanks!
According to you, `expandMz`, `expandRt` and `ppm` are some basic parameters or advanced ones?
In other words, should the users think about those parameters or the default values suit at 90%?

**Comment by jotsetung** [comment]
they will be advanced parameters. some people might want to have them (because they help avoiding that even after filling in missing peaks you still have missing values) but most will not.

**Comment by lecorguille** [comment]
Done https://github.com/workflow4metabolomics/xcms/pull/78/commits/7dda1f51107f54baf3be558893a75c9c3810fde4
Thanks again @jotsetung
