### ISSUE TITLE
Use URL as filename

### ISSUE THREAD

**Issue by RomainDallet** [workflow4metabolomics/xcms#95]
Hi @lecorguille ,

I import my data as a collection from the Paste/Fetch option using URL pointing on it, like `https://raw.githubusercontent.com/RomainDallet/DataForGIT/master/data/QC1_003.mzXML`.

My problem is that when I run the first step of the workflow (MSnbase readMSData), a new collection My_collection.raw.RData is generated, but all datasets have an error : 

```
Fatal error: Exit code 1 ()
Warning message:
In file.create(to[okay]) :
  cannot create file 'https://raw.githubusercontent.com/RomainDallet/DataForGIT/master/data/QC1_003.mzXML', reason 'No such file or directory'
Error in .testReadMSDataInput(environment()) : 
  At least one MS file is required.
Calls: readMSData -> readOnDiskMSData -> .testReadMSDataInput
Execution halted
```

Is there a problem because filenames are URL ?

**Comment by lecorguille** [comment]
In progress
xref: https://github.com/workflow4metabolomics/xcms/pull/99

Note for archive: this feature allow to create some Galaxy Interactive Tours which fetch the inputs with URL

Thanks @RomainDallet for the report

**Comment by lecorguille** [comment]
Done
